<?php
$pageTitle="Ver Denúncia"; $active="dashboard"; require_once "auth.php";
$id=(int)($_GET['id']??0); $stmt=$pdo->prepare("SELECT * FROM denuncias WHERE id=?"); $stmt->execute([$id]); $d=$stmt->fetch(PDO::FETCH_ASSOC); if(!$d) die("Denúncia não encontrada.");
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(isset($_POST['estado'])){ $stmt=$pdo->prepare("UPDATE denuncias SET estado=?, prioridade=?, observacoes_admin=? WHERE id=?"); $stmt->execute([$_POST['estado'],$_POST['prioridade'],$_POST['observacoes_admin'],$id]); }
    if(!empty(trim($_POST['mensagem']??''))){ $stmt=$pdo->prepare("INSERT INTO denuncias_mensagens (denuncia_id, origem, mensagem) VALUES (?, 'admin', ?)"); $stmt->execute([$id,trim($_POST['mensagem'])]); }
    echo "<script>window.location.href='ver.php?id=".$id."&ok=1';</script>"; exit;
}
$stmt=$pdo->prepare("SELECT * FROM denuncias_anexos WHERE denuncia_id=? ORDER BY id DESC"); $stmt->execute([$id]); $anexos=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare("SELECT * FROM denuncias_mensagens WHERE denuncia_id=? ORDER BY criado_em ASC"); $stmt->execute([$id]); $mensagens=$stmt->fetchAll(PDO::FETCH_ASSOC);
function estadoDen($e){return ['recebida'=>'Recebida','em_analise'=>'Em análise','info_solicitada'=>'Informação solicitada','encaminhada'=>'Encaminhada','concluida'=>'Concluída','arquivada'=>'Arquivada'][$e]??$e;}
require_once "layout-top.php";
?>
<style>.grid{display:grid;grid-template-columns:1fr .8fr;gap:24px}.card{background:white;border:1px solid #e5e7eb;border-radius:24px;padding:22px;margin-bottom:20px}.line{background:#f8fafc;border:1px solid #e5e7eb;border-radius:16px;padding:13px;margin-bottom:10px}.form{display:grid;gap:12px}.form select,.form textarea{width:100%;border:1px solid #dbe4ee;background:#f8fafc;border-radius:15px;min-height:48px;padding:12px;font-weight:800}.msg{background:#f8fafc;border:1px solid #e5e7eb;border-radius:16px;padding:14px;margin-bottom:10px}@media(max-width:1000px){.grid{grid-template-columns:1fr}}</style>
<div class="grid"><div><div class="card"><h2><?= htmlspecialchars($d['assunto']) ?></h2><span class="badge"><?= htmlspecialchars($d['codigo']) ?></span><span class="badge"><?= htmlspecialchars(estadoDen($d['estado'])) ?></span></div><div class="card"><h2>Dados da denúncia</h2><div class="line"><strong>Tipo:</strong> <?= htmlspecialchars($d['tipo']) ?></div><div class="line"><strong>Categoria:</strong> <?= htmlspecialchars($d['categoria']) ?></div><div class="line"><strong>Local:</strong> <?= htmlspecialchars($d['local_ocorrencia']) ?></div><div class="line"><strong>Data ocorrência:</strong> <?= htmlspecialchars($d['data_ocorrencia']) ?></div><div class="line"><strong>Anónima:</strong> <?= $d['anonima']?'Sim':'Não' ?></div><?php if(!$d['anonima']): ?><div class="line"><strong>Nome:</strong> <?= htmlspecialchars($d['nome']) ?><br><strong>Email:</strong> <?= htmlspecialchars($d['email']) ?><br><strong>Telefone:</strong> <?= htmlspecialchars($d['telefone']) ?></div><?php endif; ?><div class="line"><strong>Descrição:</strong><br><?= nl2br(htmlspecialchars($d['descricao'])) ?></div></div><div class="card"><h2>Anexos</h2><?php foreach($anexos as $a): ?><p><a class="btn secondary" href="../uploads/denuncias/<?= htmlspecialchars($a['ficheiro']) ?>" target="_blank"><i class="bi bi-paperclip"></i> <?= htmlspecialchars($a['ficheiro_original'] ?: $a['ficheiro']) ?></a></p><?php endforeach; ?><?php if(empty($anexos)): ?><p>Sem anexos.</p><?php endif; ?></div></div><div><div class="card"><h2>Gestão</h2><form method="POST" class="form"><label>Estado</label><select name="estado"><?php foreach(['recebida','em_analise','info_solicitada','encaminhada','concluida','arquivada'] as $e): ?><option value="<?= $e ?>" <?= $d['estado']===$e?'selected':'' ?>><?= estadoDen($e) ?></option><?php endforeach; ?></select><label>Prioridade</label><select name="prioridade"><option value="normal" <?= $d['prioridade']==='normal'?'selected':'' ?>>Normal</option><option value="alta" <?= $d['prioridade']==='alta'?'selected':'' ?>>Alta</option></select><label>Observações internas</label><textarea name="observacoes_admin"><?= htmlspecialchars($d['observacoes_admin']??'') ?></textarea><label>Mensagem para acompanhamento</label><textarea name="mensagem"></textarea><button class="btn">Guardar</button></form></div><div class="card"><h2>Mensagens</h2><?php foreach($mensagens as $m): ?><div class="msg"><strong><?= $m['origem']==='admin'?'Gestor de denúncias':'Denunciante' ?></strong><br><?= nl2br(htmlspecialchars($m['mensagem'])) ?><br><small><?= date('d/m/Y H:i', strtotime($m['criado_em'])) ?></small></div><?php endforeach; ?><?php if(empty($mensagens)): ?><p>Sem mensagens.</p><?php endif; ?></div></div></div>
<?php require_once "layout-bottom.php"; ?>