<?php require_once "includes/header.php"; ?>
<style>
.cd-page{background:linear-gradient(180deg,#f7f4ef,#f8fafc 45%,#fff)}
.cd-hero{padding:96px 0 118px;background:linear-gradient(135deg,rgba(36,42,50,.98),rgba(17,21,28,.94)),url('/assets/img/freguesia-1.jpg') center/cover no-repeat;color:white}
.cd-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:42px;align-items:center}
.cd-kicker{display:inline-flex;background:rgba(212,170,0,.16);border:1px solid rgba(212,170,0,.38);color:#F0D060;border-radius:999px;padding:10px 15px;font-size:13px;font-weight:900;text-transform:uppercase}
.cd-hero h1{font-size:clamp(42px,6vw,76px);line-height:1.02;margin:20px 0 18px}.cd-hero p{color:#dbeafe;font-size:20px;line-height:1.75;max-width:820px}
.cd-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.cd-btn{display:inline-flex;align-items:center;justify-content:center;background:var(--cor-secundaria);color:#11151B!important;text-decoration:none;border-radius:16px;padding:15px 20px;font-weight:900;box-shadow:0 16px 34px rgba(0,0,0,.20);transition:.25s}.cd-btn:hover{transform:translateY(-3px)}.cd-btn.secondary{background:rgba(255,255,255,.12);color:white!important;border:1px solid rgba(255,255,255,.22)}
.cd-card-hero{background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.22);backdrop-filter:blur(14px);border-radius:34px;padding:30px;box-shadow:0 32px 80px rgba(0,0,0,.25)}.cd-card-hero strong{display:block;font-size:60px;color:var(--cor-secundaria)}
.cd-shell{margin-top:-64px;position:relative;z-index:4}.cd-strip{background:white;border:1px solid #e5e7eb;border-radius:30px;padding:18px;box-shadow:0 22px 65px rgba(0,0,0,.12);display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:30px}
.cd-strip-item{background:#f8fafc;border:1px solid #eef2f7;border-radius:22px;padding:18px;display:flex;gap:13px;align-items:center}.cd-icon{width:50px;height:50px;border-radius:17px;background:var(--cor-principal);color:white;display:grid;place-items:center;font-size:24px;flex-shrink:0}
.cd-head{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;margin:36px 0 22px}.cd-head h2{color:#11151B;font-size:38px;margin:8px 0 0}.cd-head p{max-width:650px;color:#64748b;line-height:1.7}
.cd-info-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin-bottom:28px}.cd-info-card,.cd-panel{background:white;border:1px solid #eef2f7;border-radius:28px;padding:26px;box-shadow:0 18px 45px rgba(0,0,0,.08)}.cd-info-card h3,.cd-panel h2{color:#11151B}.cd-info-card p,.cd-panel p,.cd-panel li{color:#64748b;line-height:1.75;font-weight:700}
.cd-cta{background:linear-gradient(135deg,var(--cor-principal),#11151B);color:white;border-radius:30px;padding:34px;margin-bottom:44px;box-shadow:0 22px 60px rgba(0,0,0,.16)}.cd-cta p{color:#dbeafe}
@media(max-width:1050px){.cd-grid,.cd-strip,.cd-info-grid{grid-template-columns:1fr}.cd-head{display:block}}
</style>
<main class="cd-page">
<section class="cd-hero"><div class="container cd-grid"><div><span class="cd-kicker"><i class="bi bi-exclamation-triangle"></i> Plataforma de denúncias</span><h1>Canal de Denúncias</h1><p>Canal seguro para comunicação de infrações, irregularidades ou situações contrárias à ética, legalidade e boa gestão pública, com proteção do denunciante e confidencialidade.</p><div class="cd-actions"><a class="cd-btn" href="/denuncias.php">Efetuar uma denúncia aqui</a><a class="cd-btn secondary" href="/acompanhar-denuncia.php">Seguir Denúncia</a></div></div><aside class="cd-card-hero"><strong><i class="bi bi-shield-lock"></i></strong><h2>Confidencialidade</h2><p>Pode submeter a denúncia de forma anónima ou identificada, ficando disponível um código de acompanhamento.</p></aside></div></section>
<section class="section cd-shell"><div class="container">
<div class="cd-strip"><div class="cd-strip-item"><div class="cd-icon"><i class="bi bi-person-bounding-box"></i></div><div><strong>Anonimato</strong><br><span>Opção de denúncia anónima.</span></div></div><div class="cd-strip-item"><div class="cd-icon"><i class="bi bi-shield-lock"></i></div><div><strong>Sigilo</strong><br><span>Dados tratados com reserva.</span></div></div><div class="cd-strip-item"><div class="cd-icon"><i class="bi bi-paperclip"></i></div><div><strong>Anexos</strong><br><span>Envio de documentos.</span></div></div><div class="cd-strip-item"><div class="cd-icon"><i class="bi bi-search"></i></div><div><strong>Acompanhamento</strong><br><span>Consulta por código.</span></div></div></div>
<div class="cd-head"><div><span class="cd-kicker">Enquadramento</span><h2>O que pode denunciar</h2></div><p>Este canal destina-se à comunicação de factos graves ou irregularidades relacionadas com a atividade pública.</p></div>
<div class="cd-info-grid"><article class="cd-info-card"><h3><i class="bi bi-card-checklist"></i> Infrações e irregularidades</h3><p>Corrupção, favorecimento, conflitos de interesses, abuso de funções ou violação de regras aplicáveis.</p></article><article class="cd-info-card"><h3><i class="bi bi-bank"></i> Gestão pública</h3><p>Situações relacionadas com contratação pública, recursos, procedimentos administrativos ou utilização indevida de meios.</p></article><article class="cd-info-card"><h3><i class="bi bi-people-fill"></i> Ética e conduta</h3><p>Comportamentos contrários aos valores de integridade, imparcialidade, transparência e serviço público.</p></article></div>
<div class="cd-panel"><h2>Garantias do denunciante</h2><ul><li>Possibilidade de apresentação de denúncia anónima.</li><li>Tratamento confidencial da informação comunicada.</li><li>Possibilidade de anexar documentos ou imagens.</li><li>Acompanhamento posterior através de código único.</li></ul></div>
<div class="cd-panel"><h2>Legislação e enquadramento</h2><p>Este canal inspira-se no Regime Geral de Proteção de Denunciantes de Infrações, previsto na Lei n.º 93/2021, e nos princípios de transparência, ética, integridade e prevenção de irregularidades na Administração Pública.</p></div>
<div class="cd-cta"><h2>Pronto para comunicar uma situação?</h2><p>Depois de submeter a denúncia, guarde o código gerado para poder acompanhar o processo.</p><div class="cd-actions"><a class="cd-btn" href="/denuncias.php">Efetuar uma denúncia aqui</a><a class="cd-btn secondary" href="/acompanhar-denuncia.php">Seguir Denúncia</a></div></div>
</div></section></main>
<?php require_once "includes/footer.php"; ?>
