<?php
require_once "includes/auth.php";
if (!canManageDenuncias()) { die("Acesso reservado ao Canal de Denúncias."); }

$adminPageTitle = "Canal de Denúncias";
$adminActive = "denuncias";
require_once "includes/header.php";

$total=(int)$pdo->query("SELECT COUNT(*) FROM denuncias")->fetchColumn(); $recebidas=(int)$pdo->query("SELECT COUNT(*) FROM denuncias WHERE estado='recebida'")->fetchColumn(); $analise=(int)$pdo->query("SELECT COUNT(*) FROM denuncias WHERE estado='em_analise'")->fetchColumn(); $concluidas=(int)$pdo->query("SELECT COUNT(*) FROM denuncias WHERE estado='concluida'")->fetchColumn(); $denuncias=$pdo->query("SELECT * FROM denuncias ORDER BY criado_em DESC")->fetchAll(PDO::FETCH_ASSOC); function estadoDen($e){return ['recebida'=>'Recebida','em_analise'=>'Em análise','info_solicitada'=>'Informação solicitada','encaminhada'=>'Encaminhada','concluida'=>'Concluída','arquivada'=>'Arquivada'][$e]??$e;} ?>
<style>.den-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}.den-stat{background:white;border-radius:22px;padding:22px;box-shadow:0 12px 30px rgba(0,0,0,.06)}.den-stat strong{display:block;color:#242A30;font-size:34px}.den-row{background:white;border:1px solid #e5e7eb;border-radius:18px;padding:16px;margin-bottom:12px;display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center}.den-row h3{margin:0 0 6px;color:#11151B}.badge{display:inline-flex;background:#eef2ff;color:#242A30;border-radius:999px;padding:6px 9px;font-size:12px;font-weight:900;margin-right:5px}.badge.alta{background:#fee2e2;color:#991b1b}@media(max-width:900px){.den-stats,.den-row{grid-template-columns:1fr}}</style>
<div class="den-stats"><div class="den-stat"><strong><?= $total ?></strong><span>Total</span></div><div class="den-stat"><strong><?= $recebidas ?></strong><span>Recebidas</span></div><div class="den-stat"><strong><?= $analise ?></strong><span>Em análise</span></div><div class="den-stat"><strong><?= $concluidas ?></strong><span>Concluídas</span></div></div>
<?php foreach($denuncias as $d): ?><div class="den-row"><div><h3><?= htmlspecialchars($d['assunto']) ?></h3><span class="badge"><?= htmlspecialchars($d['codigo']) ?></span><span class="badge"><?= htmlspecialchars(estadoDen($d['estado'])) ?></span><span class="badge <?= $d['prioridade']==='alta'?'alta':'' ?>"><?= htmlspecialchars($d['prioridade']) ?></span><span class="badge"><?= htmlspecialchars($d['categoria']) ?></span></div><div><a class="btn" href="ver_denuncia.php?id=<?= (int)$d['id'] ?>">Ver denúncia</a></div></div><?php endforeach; ?><?php if(empty($denuncias)): ?><div class="table-box">Ainda não existem denúncias.</div><?php endif; ?><?php require_once "includes/footer.php"; ?>